# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gymhop_frontend' do
  pod 'Stripe', '~> 14.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gymhop_frontend

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'gymhop_frontendTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

