require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'gymhop_frontend' do
  

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Pods for gymhop_frontend
  pod 'Stripe', '~> 14.0.0'

  # pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

end

