
/*                              All users                                        */

//AUTH
export const POST_USER_LOGIN_PENDING = "POST_USER_LOGIN_PENDING";
export const POST_USER_LOGIN_SUCCESS = "POST_USER_LOGIN_SUCCESS";
export const POST_USER_LOGIN_FAILURE = "POST_USER_LOGIN_FAILURE";

export const LOG_OUT_USER = "LOG_OUT_USER";

export const SET_USER_TOKEN = "SET_USER_TOKEN";

export const POST_USER_PENDING = "POST_USER_PENDING";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_FAILURE = "POST_USER_FAILURE";
export const CLEAR_REGISTRATION_ERRORS = "CLEAR_REGISTRATION_ERRORS";

// user details
export const GET_USER_DETAILS_PENDING = "GET_USER_DETAILS_PENDING";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";

export const UPDATE_USER_DETAILS_PENDING = "UPDATE_USER_DETAILS_PENDING";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE";

// payments
export const CREATE_SUBSCRIPTION_CHARGE_PENDING = "CREATE_SUBSCRIPTION_CHARGE_PENDING";
export const CREATE_SUBSCRIPTION_CHARGE_FAILURE = "CREATE_SUBSCRIPTION_CHARGE_FAILURE";
export const CREATE_SUBSCRIPTION_CHARGE_SUCCESS = "CREATE_SUBSCRIPTION_CHARGE_SUCCESS";

// gyms
export const GET_GYMS_PENDING = "GET_GYMS_PENDING";
export const GET_GYMS_SUCCESS = "GET_GYMS_SUCCESS";
export const GET_GYMS_FAILURE = "GET_GYMS_FAILURE";

export const UI_SELECT_GYM = "UI_SELECT_GYM";

//check ins
export const POST_CHECKIN_PENDING = "POST_CHECKIN_PENDING";
export const POST_CHECKIN_SUCCESS = "POST_CHECKIN_SUCCESS";
export const POST_CHECKIN_FAILURE = "POST_CHECKIN_FAILURE";

/*                              Gym owners                                        */

// statistics
export const GET_GYM_STATISTICS_PENDING = "GET_GYM_STATISTICS_PENDING";
export const GET_GYM_STATISTICS_SUCCESS = "GET_GYM_STATISTICS_SUCCESS";
export const GET_GYM_STATISTICS_FAILURE = "GET_GYM_STATISTICS_FAILURE";

// UI config
export const PULLUP_MENU_LEVEL = "PULLUP_MENU_LEVEL";
