
//user
export const POST_USER_LOGIN_PENDING = "POST_USER_LOGIN_PENDING";
export const POST_USER_LOGIN_SUCCESS = "POST_USER_LOGIN_SUCCESS";
export const POST_USER_LOGIN_FAILURE = "POST_USER_LOGIN_FAILURE";


export const POST_USER_PENDING = "POST_USER_PENDING";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_FAILURE = "POST_USER_FAILURE";

export const GET_USER_DETAILS_PENDING = "GET_USER_DETAILS_PENDING";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";



// gyms
export const GET_GYMS_PENDING = "GET_GYMS_PENDING";
export const GET_GYMS_SUCCESS = "GET_GYMS_SUCCESS";
export const GET_GYMS_FAILURE = "GET_GYMS_FAILURE";

//check ins
export const POST_CHECKIN_PENDING = "POST_CHECKIN_PENDING";
export const POST_CHECKIN_SUCCESS = "POST_CHECKIN_SUCCESS";
export const POST_CHECKIN_FAILURE = "POST_CHECKIN_FAILURE";
