
// gyms
export const GET_GYMS_PENDING = "GET_GYMS_PENDING";
export const GET_GYMS_FAILURE = "GET_GYMS_FAILURE";
export const GET_GYMS_SUCCESS = "GET_GYMS_SUCCESS";

//check ins
export const POST_CHECKIN_PENDING = "POST_CHECKIN_PENDING";
export const POST_CHECKIN_FAILURE = "POST_CHECKIN_FAILURE";
export const POST_CHECKIN_SUCCESS = "POST_CHECKIN_SUCCESS"; 
